/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Client-side COM declarations for ${GROUP_NAME}: per-interface vtable
 * structs, default thunk prototypes, default vtable populators, and default
 * constructors.
 *
 * The thunk bodies, populators, and constructors live in the matching .c
 * file.  This split keeps the headers small and prevents N copies of the
 * thunk code from landing in every TU that pulls in this family.
 */

#ifndef NPT_PROTOCOL_CLIENT_${GUARD}_H
#define NPT_PROTOCOL_CLIENT_${GUARD}_H

#include "npt_protocol_guest_${GROUP_NAME}.h"
<%
# Collect parent families (for non-self-family parents) so we can include
# their client headers and get the extern thunk declarations for the
# inherited methods.
_parent_families_seen = set()
parent_family_includes = []
for _iface in INTERFACES:
    p = _iface.parent
    if p is not None and p.name != 'IUnknown':
        fam = p.family
        if fam and fam != GROUP_NAME and fam not in _parent_families_seen:
            _parent_families_seen.add(fam)
            parent_family_includes.append(fam)
%>\
% for fam in parent_family_includes:
#include "npt_protocol_client_${fam}.h"
% endfor

/* Forward-declare struct npt_device so the client_create prototypes don't
 * trigger the "declared inside parameter list" warning.  The full
 * definition lives in the consumer's npt_device.h, which the .c file pulls
 * in via npt_com.h. */
struct npt_device;

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"

<%
def fmt_param_decl(p):
    return GEN.param_decl(p)
def fmt_param_list(method):
    parts = ['void *self']
    for p in method.params:
        parts.append(fmt_param_decl(p))
    return ', '.join(parts)
def thunk_name(iface_name, method_name):
    return GEN.thunk_name(iface_name, method_name)

def ret_type(method):
    return GEN.ret_type_str(method.return_type)
%>\

% for iface in INTERFACES:
<%
    iface_lower = iface.name.lower()
    chain_methods = list(iface.iter_vtable_methods())
    own_methods = [(iface, m) for m in iface.methods]
%>\

/* ================================================================== */
/* ${iface.name}                                                       */
/* ================================================================== */

/*
 * Vtable struct in COM ABI order: slots 0-2 are IUnknown, then the
 * inherited methods from each ancestor (topmost first), then this
 * interface's own methods.  Layout-compatible with the Windows SDK's
 * ${iface.name}Vtbl, by construction.
 */
struct npt_${iface_lower}_client_vtbl {
    /* IUnknown (slots 0-2) */
    HRESULT (NPT_STDMETHODCALLTYPE *QueryInterface)(void *self, REFIID riid, void **ppvObject);
    ULONG   (NPT_STDMETHODCALLTYPE *AddRef)(void *self);
    ULONG   (NPT_STDMETHODCALLTYPE *Release)(void *self);
% for owner, method in chain_methods:
    /* slot ${method.vtable_index}: ${owner.name}::${method.name} */
    ${ret_type(method)} (NPT_STDMETHODCALLTYPE *${method.name})(${fmt_param_list(method)});
% endfor
};

/* Default thunk prototypes for the methods OWNED by this interface
 * (inherited methods are declared by their owning interface's client
 * header, included above).  Bodies live in the matching .c file.  Methods
 * marked skip_default get a generated stub that aborts at runtime via
 * npt_com_assert_overridden; the consumer must patch the vtable slot
 * with a real implementation before the method is called. */
% for _, method in own_methods:
extern ${ret_type(method)} NPT_STDMETHODCALLTYPE
${thunk_name(iface.name, method.name)}(${fmt_param_list(method)});
% endfor

/* Default IUnknown thunks for ${iface.name}.  AddRef/Release route through
 * the runtime helpers; QueryInterface walks this interface's parent IID
 * chain, falling through to a host COM_QUERY_INTERFACE round-trip on miss. */
extern HRESULT NPT_STDMETHODCALLTYPE
npt_${iface_lower}_default_QueryInterface(void *self, REFIID riid, void **ppvObject);
extern ULONG NPT_STDMETHODCALLTYPE
npt_${iface_lower}_default_AddRef(void *self);
extern ULONG NPT_STDMETHODCALLTYPE
npt_${iface_lower}_default_Release(void *self);

/* Populate `dst` with all default thunks (own + inherited via the
 * extern decls from the parent client header).  Hand-written code can
 * then patch individual slots before installing the vtable. */
extern void
npt_${iface_lower}_fill_default_vtbl(struct npt_${iface_lower}_client_vtbl *dst);

/* Per-interface default vtbl storage shared by all client instances of
 * this interface.  Populated once at runtime init by
 * npt_${iface_lower}_install_default_vtbl() (called from the global
 * npt_com_init_default_ctors populator). */
extern struct npt_${iface_lower}_client_vtbl npt_${iface_lower}_default_vtbl_storage;
extern void
npt_${iface_lower}_install_default_vtbl(void);

/* Default constructor for the wrapper cache.  Allocates a bare
 * `struct npt_com_base`, installs the default vtable, and returns it. */
extern void *
npt_${iface_lower}_client_create(struct npt_device *dev, uint64_t host_id);

% endfor

#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_CLIENT_${GUARD}_H */
