/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Global IID -> default-constructor registration.  Called once from
 * npt_com_init() in the consumer (mesa).
 */

#include "npt_com.h"
#include "npt_protocol_client_table.h"

% for family in ALL_FAMILIES:
#include "npt_protocol_client_${family}.h"
% endfor

void
npt_com_init_default_ctors(void)
{
    /* Populate every per-interface default vtable.  Must run before
     * any client_create call so the wrapper has a usable vtbl. */
% for iface in ALL_INTERFACES:
    npt_${iface.name.lower()}_install_default_vtbl();
% endfor

    /* Register every default constructor in the IID -> ctor table. */
% for iface in ALL_INTERFACES:
    npt_com_register_default_ctor(&NPT_IID_${iface.name},
                                  npt_${iface.name.lower()}_client_create);
% endfor
}
