/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Client-side COM implementation for ${GROUP_NAME}: out-of-line default
 * thunks, default vtable populators, and default constructors for every
 * interface in this family.
 */

#include "npt_protocol_client_${GROUP_NAME}.h"
#include "npt_com.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wunused-variable"

<%
def fmt_param_decl(p):
    return GEN.param_decl(p)

def thunk_name(iface_name, method_name):
    return GEN.thunk_name(iface_name, method_name)

def call_args(method):
    """Args to pass to the generated npt_call_/npt_async_ function."""
    return ['npt_com_self_ring(self)', 'npt_com_self_id(self)'] + [p.name for p in method.params]

def find_riid_param(method):
    """Find an IID input parameter (used by methods like GetBuffer /
    OpenSharedResource that take an out-param void** along with a
    runtime IID).  Returns the parameter name or None."""
    for p in method.params:
        if p.input and not p.output and p.type_name == 'IID':
            return p.name
    return None

def _count_c_expr(method, count_field_name):
    """Resolve a count field name to a C expression.

    If the count parameter is a plain UINT (indirection 0), return
    its name directly (e.g. 'NumBuffers').  If it's a UINT*
    (indirection 1, i.e. an in/out count pointer like
    pNumClassInstances), return '*pNumClassInstances' so we read
    the value the host wrote back. We already validated that indirection
    cannot be > 1"""
    for cp in method.params:
        if cp.name == count_field_name:
            if cp.indirection == 1:
                return f'*{count_field_name}'
            elif cp.indirection == 0:
                return count_field_name
    raise ValueError(f"count field '{count_field_name}' not found or is invalid in params for {method.name}")

def output_com_handle_params(method):
    """List of (param, c_type_name, iid_expr, count_expr) for output
    COM handle params.

    `c_type_name` is the type as written in the SDK (used for casts).
    `iid_expr` is the C expression to pass as the IID to
    npt_com_get_or_wrap.
    `count_expr` is the C expression for the array element count, or
    None for a single (non-array) output handle.

    For typed outputs (e.g. ID3D11Buffer **), `iid_expr` is
    '&NPT_IID_<canonical>' with type aliases resolved.  For void **
    outputs that come with a REFIID parameter (e.g. GetBuffer,
    OpenSharedResource), it's the riid parameter name itself.  void **
    outputs WITHOUT an accompanying REFIID can't be wrapped and are
    skipped.
    """
    riid_name = find_riid_param(method)
    out = []
    for p in method.params:
        if p.output and p.is_com_handle and p.indirection >= 1:
            c_type = p.type_name
            if c_type == 'void':
                if riid_name is None:
                    continue
                iid_expr = riid_name  # already a const GUID *
            else:
                iid_expr = '&NPT_IID_' + GEN.reg.resolve_alias_chain(c_type)
            # Determine array count from the registry's count field.
            count_expr = None
            if p.count is not None and isinstance(p.count, str):
                count_expr = _count_c_expr(method, p.count)
            out.append((p, c_type, iid_expr, count_expr))
    return out

def ret_type_str(method):
    return GEN.ret_type_str(method.return_type)

def fallback_ret(method):
    if not GEN.has_return(method.return_type):
        return ''
    if method.return_type == 'HRESULT':
        return '(HRESULT)0x80004005 /* E_FAIL */'
    if GEN.is_scalar_return(method.return_type):
        return f'({method.return_type})0'
    return f'({method.return_type}){{0}}'
%>\

% for iface in INTERFACES:
<%
    iface_lower = iface.name.lower()
    chain_methods = list(iface.iter_vtable_methods())
    own_methods = iface.methods
    parent_chain_names = iface.parent_iid_chain_names()
%>\

/* ================================================================== */
/* ${iface.name}                                                       */
/* ================================================================== */

/* Parent IID chain for QueryInterface fast-path.  NULL-terminated list of
 * IID pointers; QI returns self for any IID in this list. */
static const GUID *const npt_${iface_lower}_parent_iids[] = {
% for n in parent_chain_names:
    &NPT_IID_${n},
% endfor
    NULL,
};

HRESULT NPT_STDMETHODCALLTYPE
npt_${iface_lower}_default_QueryInterface(void *self, REFIID riid, void **ppvObject)
{
    HRESULT hr = npt_com_default_query_interface_chain(
        self, riid, ppvObject, npt_${iface_lower}_parent_iids);
    if (hr == NPT_S_OK)
        return hr;
    /* Pre-allocate the guest id and speculatively build the wrapper
     * BEFORE the host round-trip.  On E_NOINTERFACE the wrapper is
     * never used (the host rejected the QI, so its id is unregistered)
     * and we must Release the speculative wrapper to keep the refcount
     * straight.  The host round-trip carries just HRESULT. */
    uint64_t _guest_id = npt_com_allocate_next_id();
    /* Pass `self` as parent so the new wrapper inherits its instance_ring
     * (DC/SC shared ring pinning).  QI typically returns the same host
     * pointer as `self`, so the cache hit short-circuits before any new
     * wrapper is created -- but on the cache-miss path the new wrapper
     * must inherit the same ring or generated methods on the QI'd
     * interface would scatter onto a different host dispatch thread
     * than every other method on the same underlying object. */
    void *wrapper = npt_com_get_or_wrap(
        npt_com_self_device(self), riid, _guest_id,
        (struct npt_com_base *)self);
    if (!wrapper) {
        if (ppvObject) *ppvObject = NULL;
        return NPT_E_OUTOFMEMORY;
    }
    HRESULT host_hr = npt_com_send_query_interface(
        npt_com_self_device(self),
        npt_com_self_id(self),
        riid, _guest_id);
    if (host_hr == NPT_S_OK) {
        if (ppvObject)
            *ppvObject = wrapper;
        return NPT_S_OK;
    }
    /* QI failed host-side: the guest_id stays unregistered.  Release the
     * speculative wrapper so the guest-side refcount drains cleanly.
     * (npt_com_default_release still issues COM_RELEASE to the host,
     * which is a no-op there because the id was never registered.) */
    struct npt_com_base *com = wrapper;
    typedef ULONG (NPT_STDMETHODCALLTYPE *release_fn_t)(void *);
    ((release_fn_t)com->lpVtbl[2])(com);
    if (ppvObject) *ppvObject = NULL;
    return host_hr;
}

ULONG NPT_STDMETHODCALLTYPE
npt_${iface_lower}_default_AddRef(void *self)
{
    return npt_com_default_addref(self);
}

ULONG NPT_STDMETHODCALLTYPE
npt_${iface_lower}_default_Release(void *self)
{
    return npt_com_default_release(self);
}

% for method in own_methods:
<%
    fname = f'{iface.name}_{method.name}'
    tname = thunk_name(iface.name, method.name)
    rt = ret_type_str(method)
    has_ret = GEN.has_return(method.return_type)
    out_handles = output_com_handle_params(method)
    # Output COM handles are marshaled as guest-allocated ids in the
    # command body (no reply round-trip).  For the sync-vs-async
    # decision they do not count as "outputs".
    has_non_handle_output = any(
        p.output and not GEN.is_output_com_handle(p)
        for p in method.params
    )
    # HRESULT-only returns are async-eligible under the deferred-fatal
    # model: a failed create leaves the guest_id unregistered on the
    # host, and the next method dispatched against that id trips
    # decoder_fatal.  Other scalar returns (BOOL, UINT, etc.) and
    # struct returns still need a sync reply to deliver the value.
    is_hresult_ret = method.return_type == 'HRESULT'
    has_sync_ret = has_ret and not is_hresult_ret
    # Output COM handles are a *conditional* sync driver: sync when
    # the device has multi-ring enabled, async otherwise.
    #
    # The race only exists with multi-ring: thread A may create on its
    # TLS ring, then use the new wrapper on DC's instance ring.  Those
    # dispatch on two host threads, and the Use-side lookup can race
    # ahead of the Create-side register.  Sync forces the host register
    # to commit before the caller gets the wrapper.
    #
    # With multi-ring off, every submit lands on the single primary
    # ring in FIFO order, so Create-then-Use on the same ring cannot
    # race.  Async is safe and measurably faster (see
    # docs/performance-analysis-2026-04-17-phase1-3.md: 2.37x loading
    # throughput when Create* is async).
    #
    # Compile-time we can't know which mode runs, so we emit a runtime
    # branch on dev->multi_ring_enabled.  The bool is set once at
    # device creation, so the branch predictor always pins it after
    # the first call.  D3D12 will unconditionally set the flag true
    # at device-create time, so D3D12's path is always sync -- fine,
    # since D3D12's fan-out-heavy workload amortizes the sync cost
    # over many parallel recorders.
    has_output_com_handles = bool(out_handles)
    # force_sync (registry annotation) is for methods whose HRESULT
    # carries control-flow meaning rather than fatal-error semantics --
    # e.g. enumeration terminators like EnumOutputs / EnumAdapters
    # signal end-of-iteration with DXGI_ERROR_NOT_FOUND, and the
    # async/deferred-fatal path would mask that into a fake S_OK and
    # make the caller loop forever.
    always_sync = has_non_handle_output or has_sync_ret or method.force_sync
    maybe_sync = has_output_com_handles and not always_sync
    # `needs_sync` is kept for the wrapper-build guard below: it
    # controls whether we use NPT_SUCCEEDED(_ret) vs a bare NULL check.
    # Under `maybe_sync`, _ret is real HRESULT in sync mode and S_OK
    # (0) in async mode, so NPT_SUCCEEDED works in both.  Under
    # `always_sync`, _ret is a real value.  Under pure async there
    # is no _ret for the guard (but there are also no handles to guard).
    needs_sync = always_sync or maybe_sync

    # Safety check: output COM handle arrays use their count expression
    # to iterate and wrap elements after npt_call_ returns.  If the
    # method can fail (returns HRESULT) and the count comes from an
    # indirect output parameter (UINT *, written by the host), the
    # count may be valid (host writes the "required" size) but the
    # array contents may be garbage on failure.  We currently don't
    # guard the wrapping loop with an HRESULT check because all known
    # cases are either void-return (always succeed) or use a plain
    # input UINT count (caller-controlled, always valid).  Assert
    # this invariant so a future registry addition trips a build error
    # rather than silently producing unsafe code.
    array_handles  = [(p, ct, iid, ce) for p, ct, iid, ce in out_handles if ce is not None]
    if has_ret and array_handles:
        for ah_p, ah_ct, ah_iid, ah_ce in array_handles:
            # Find the count param and check its properties
            count_name = ah_p.count
            for cp in method.params:
                if cp.name == count_name and cp.indirection >= 1 and cp.output:
                    raise RuntimeError(
                        f'{iface.name}::{method.name}: output COM handle array '
                        f'\'{ah_p.name}\' uses indirect output count '
                        f'\'{count_name}\' on a method that returns {method.return_type}. '
                        f'The generated wrapping loop does not guard against '
                        f'failure — the count may be valid but the array contents '
                        f'are garbage when HRESULT != S_OK.  Either mark this '
                        f'method skip_default in the overlay and write a hand-'
                        f'written override, or add HRESULT-guarded wrapping to '
                        f'the client template.'
                    )
%>\
% if method.skip_default:
/* skip_default: ${iface.name}::${method.name} -- override required.
 * The default body aborts loudly so a missing override is a runtime
 * failure rather than a silent data drop. */
${rt} NPT_STDMETHODCALLTYPE
${tname}(\
void *self\
% for p in method.params:
, ${fmt_param_decl(p)}\
% endfor
)
{
    (void)self;
% for p in method.params:
    (void)${p.name};
% endfor
    npt_com_assert_overridden("${iface.name}", "${method.name}");
% if has_ret:
    return ${fallback_ret(method)};
% endif
}

% else:
${rt} NPT_STDMETHODCALLTYPE
${tname}(\
void *self\
% for p in method.params:
, ${fmt_param_decl(p)}\
% endfor
)
{
<%
    # Partition output COM handles into single-value vs array.
    #
    # The encoder allocates a guest_id for each output COM handle slot
    # and stashes it (cast through uintptr_t) into the caller's pointer.
    # After npt_async_ / npt_call_ returns, the client thunk reads that
    # slot back as a uint64_t id and converts it to a proper wrapper via
    # npt_com_get_or_wrap.  Both the sync and async paths share this
    # post-call "stash -> wrap" conversion.
    single_handles = [(p, ct, iid, ce) for p, ct, iid, ce in out_handles if ce is None]
    array_handles  = [(p, ct, iid, ce) for p, ct, iid, ce in out_handles if ce is not None]
%>\
% if single_handles:
% for p, c_type, iid_expr, _ in single_handles:
    ${c_type} *_raw_${p.name} = NULL;
% endfor
    /* Redirect each single-output pointer to a local _raw_ slot so the
     * encoder's stashed guest_id lands somewhere we can read after the
     * submit returns; the original caller-side pointers are restored
     * with the wrapped result at the end. */
% for p, c_type, iid_expr, _ in single_handles:
    ${c_type} **_orig_${p.name} = ${p.name};
    if (${p.name})
        ${p.name} = (${c_type} **)&_raw_${p.name};
% endfor
% endif
% if always_sync:
% if has_ret:
    ${method.return_type} _ret = npt_call_${fname}(\
% else:
    npt_call_${fname}(\
% endif
% for i, a in enumerate(call_args(method)):
${a}${',' if i < len(call_args(method)) - 1 else ''}\
% endfor
);
% elif maybe_sync:
    /* Runtime-conditional sync: with multi_ring_enabled the caller may
     * use the new handle on a different ring, so we must wait for the
     * host register.  With multi_ring off, all traffic is FIFO-ordered
     * on primary and async is race-free. */
% if has_ret:
    ${method.return_type} _ret;
% endif
    if (npt_com_self_device(self)->multi_ring_enabled) {
% if has_ret:
        _ret = npt_call_${fname}(\
% else:
        npt_call_${fname}(\
% endif
% for i, a in enumerate(call_args(method)):
${a}${',' if i < len(call_args(method)) - 1 else ''}\
% endfor
);
    } else {
        npt_async_${fname}(\
% for i, a in enumerate(call_args(method)):
${a}${',' if i < len(call_args(method)) - 1 else ''}\
% endfor
);
% if has_ret:
        _ret = (${method.return_type})0;  /* deferred-fatal: assume S_OK */
% endif
    }
% else:
    npt_async_${fname}(\
% for i, a in enumerate(call_args(method)):
${a}${',' if i < len(call_args(method)) - 1 else ''}\
% endfor
);
% endif
% if single_handles:
% for p, c_type, iid_expr, _ in single_handles:
    if (_orig_${p.name}) {
% if needs_sync and has_ret and method.return_type == 'HRESULT':
        /* Sync HRESULT: discard the stashed id on failure -- the host
         * won't have registered it, so any wrapper we build would be
         * bogus.  Under the deferred-fatal model an unregistered id
         * surfaces at first use, but returning the right HRESULT here
         * lets well-behaved callers short-circuit without an allocation. */
        if (NPT_SUCCEEDED((HRESULT)_ret) && _raw_${p.name})
% else:
        if (_raw_${p.name})
% endif
            *_orig_${p.name} = (${c_type} *)npt_com_get_or_wrap(
                npt_com_self_device(self),
                ${iid_expr},
                (uint64_t)(uintptr_t)_raw_${p.name},
                (struct npt_com_base *)self);
        else
            *_orig_${p.name} = NULL;
    }
% endfor
% endif
% if array_handles:
    /* Wrap output COM handle arrays in-place.  The encoder stashed the
     * guest-allocated ids in each slot before the submit; convert them
     * to wrappers now. */
% for p, c_type, iid_expr, count_expr in array_handles:
    if (${p.name}) {
        const UINT _n_${p.name} = (UINT)(${count_expr});
        for (UINT _i = 0; _i < _n_${p.name}; _i++) {
            if (${p.name}[_i])
                ${p.name}[_i] = (${c_type} *)npt_com_get_or_wrap(
                    npt_com_self_device(self),
                    ${iid_expr},
                    (uint64_t)(uintptr_t)${p.name}[_i],
                    (struct npt_com_base *)self);
        }
    }
% endfor
% endif
% if has_ret:
% if needs_sync:
    return _ret;
% else:
    /* Async under the deferred-fatal model: assume success.  Host-side
     * failures (OOM, bad arg) leave the guest_id unregistered, so the
     * first method call against the wrapper trips decoder_fatal and
     * unwinds the context cleanly. */
    return (${method.return_type})0 /* S_OK */;
% endif
% endif
}

% endif
% endfor

void
npt_${iface_lower}_fill_default_vtbl(struct npt_${iface_lower}_client_vtbl *dst)
{
    dst->QueryInterface = npt_${iface_lower}_default_QueryInterface;
    dst->AddRef         = npt_${iface_lower}_default_AddRef;
    dst->Release        = npt_${iface_lower}_default_Release;
% for owner, method in chain_methods:
    dst->${method.name} = ${thunk_name(owner.name, method.name)};
% endfor
}

/*
 * Per-interface default vtbl storage.  Populated by
 * npt_${iface_lower}_install_default_vtbl(), which is called once at
 * runtime init time from the global client_table init function.
 */
struct npt_${iface_lower}_client_vtbl npt_${iface_lower}_default_vtbl_storage;

void
npt_${iface_lower}_install_default_vtbl(void)
{
    npt_${iface_lower}_fill_default_vtbl(&npt_${iface_lower}_default_vtbl_storage);
}

void *
npt_${iface_lower}_client_create(struct npt_device *dev, uint64_t host_id)
{
    struct npt_com_base *p = (struct npt_com_base *)npt_alloc(sizeof(*p));
    if (!p)
        return NULL;
    npt_com_base_init(p,
        (const void **)&npt_${iface_lower}_default_vtbl_storage,
        dev, host_id);
    return p;
}

% endfor

#pragma GCC diagnostic pop
