/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Client-side COM implementation for ${GROUP_NAME}: out-of-line default
 * thunks, default vtable populators, and default constructors for every
 * interface in this family.
 */

#include "npt_protocol_client_${GROUP_NAME}.h"
#include "npt_com.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wunused-variable"

<%
def fmt_param_decl(p):
    return GEN.param_decl(p)

def thunk_name(iface_name, method_name):
    return GEN.thunk_name(iface_name, method_name)

def call_args(method):
    """Args to pass to the generated npt_call_/npt_async_ function."""
    return ['npt_com_self_ring(self)', 'npt_com_self_id(self)'] + [p.name for p in method.params]

def find_riid_param(method):
    """Find an IID input parameter (used by methods like GetBuffer /
    OpenSharedResource that take an out-param void** along with a
    runtime IID).  Returns the parameter name or None."""
    for p in method.params:
        if p.input and not p.output and p.type_name == 'IID':
            return p.name
    return None

def _count_c_expr(method, count_field_name):
    """Resolve a count field name to a C expression.

    If the count parameter is a plain UINT (indirection 0), return
    its name directly (e.g. 'NumBuffers').  If it's a UINT*
    (indirection 1, i.e. an in/out count pointer like
    pNumClassInstances), return '*pNumClassInstances' so we read
    the value the host wrote back. We already validated that indirection
    cannot be > 1"""
    for cp in method.params:
        if cp.name == count_field_name:
            if cp.indirection == 1:
                return f'*{count_field_name}'
            elif cp.indirection == 0:
                return count_field_name
    raise ValueError(f"count field '{count_field_name}' not found or is invalid in params for {method.name}")

def output_com_handle_params(method):
    """List of (param, c_type_name, iid_expr, count_expr) for output
    COM handle params.

    `c_type_name` is the type as written in the SDK (used for casts).
    `iid_expr` is the C expression to pass as the IID to
    npt_com_get_or_wrap.
    `count_expr` is the C expression for the array element count, or
    None for a single (non-array) output handle.

    For typed outputs (e.g. ID3D11Buffer **), `iid_expr` is
    '&NPT_IID_<canonical>' with type aliases resolved.  For void **
    outputs that come with a REFIID parameter (e.g. GetBuffer,
    OpenSharedResource), it's the riid parameter name itself.  void **
    outputs WITHOUT an accompanying REFIID can't be wrapped and are
    skipped.
    """
    riid_name = find_riid_param(method)
    out = []
    for p in method.params:
        if p.output and p.is_com_handle and p.indirection >= 1:
            c_type = p.type_name
            if c_type == 'void':
                if riid_name is None:
                    continue
                iid_expr = riid_name  # already a const GUID *
            else:
                iid_expr = '&NPT_IID_' + GEN.reg.resolve_alias_chain(c_type)
            # Determine array count from the registry's count field.
            count_expr = None
            if p.count is not None and isinstance(p.count, str):
                count_expr = _count_c_expr(method, p.count)
            out.append((p, c_type, iid_expr, count_expr))
    return out

def ret_type_str(method):
    # Aggregate returns use the COM x64 hidden-return-pointer ABI: the
    # thunk takes a `RET *_ret_out` right after `self` and returns it.
    if GEN.is_aggregate_return(method.return_type):
        return f'{method.return_type} *'
    return GEN.ret_type_str(method.return_type)

def fallback_ret(method):
    if not GEN.has_return(method.return_type):
        return ''
    if method.return_type == 'HRESULT':
        return '(HRESULT)0x80004005 /* E_FAIL */'
    if GEN.is_scalar_return(method.return_type):
        return f'({method.return_type})0'
    return f'({method.return_type}){{0}}'
%>\

% for iface in INTERFACES:
<%
    iface_lower = iface.name.lower()
    chain_methods = list(iface.iter_vtable_methods())
    own_methods = iface.methods
    parent_chain_names = iface.parent_iid_chain_names()
%>\

/* ================================================================== */
/* ${iface.name}                                                       */
/* ================================================================== */

/* Parent IID chain for QueryInterface fast-path.  NULL-terminated list of
 * IID pointers; QI returns self for any IID in this list. */
static const GUID *const npt_${iface_lower}_parent_iids[] = {
% for n in parent_chain_names:
    &NPT_IID_${n},
% endfor
    NULL,
};

HRESULT NPT_STDMETHODCALLTYPE
npt_${iface_lower}_default_QueryInterface(void *self, REFIID riid, void **ppvObject)
{
    HRESULT hr = npt_com_default_query_interface_chain(
        self, riid, ppvObject, npt_${iface_lower}_parent_iids);
    if (hr == NPT_S_OK)
        return hr;
    /* Derived/sibling IIDs are resolved against the host object, one
     * wire round trip per (object, IID) lifetime: the runtime memoizes
     * the verdict and the wrapper on `self` (npt_com.c). */
    return npt_com_query_interface_host(self, riid, ppvObject);
}

ULONG NPT_STDMETHODCALLTYPE
npt_${iface_lower}_default_AddRef(void *self)
{
    return npt_com_default_addref(self);
}

ULONG NPT_STDMETHODCALLTYPE
npt_${iface_lower}_default_Release(void *self)
{
    return npt_com_default_release(self);
}

% for method in own_methods:
<%
    fname = f'{iface.name}_{method.name}'
    tname = thunk_name(iface.name, method.name)
    rt = ret_type_str(method)
    has_ret = GEN.has_return(method.return_type)
    is_agg = GEN.is_aggregate_return(method.return_type)
    out_handles = output_com_handle_params(method)
    # Sync-vs-async: GEN.method_always_sync (npt_codegen.py) is the one
    # statement of the rule.
    always_sync = GEN.method_always_sync(method)
    # `needs_sync` drives the wrapper-build guard below: with a real
    # HRESULT the guard is NPT_SUCCEEDED(_ret); a pure-async Create
    # guards on the stashed id alone.
    needs_sync = always_sync

    # Safety check: output COM handle arrays use their count expression
    # to iterate and wrap elements after npt_call_ returns.  If the
    # method can fail (returns HRESULT) and the count comes from an
    # indirect output parameter (UINT *, written by the host), the
    # count may be valid (host writes the "required" size) but the
    # array contents may be garbage on failure.  We currently don't
    # guard the wrapping loop with an HRESULT check because all known
    # cases are either void-return (always succeed) or use a plain
    # input UINT count (caller-controlled, always valid).  Assert
    # this invariant so a future registry addition trips a build error
    # rather than silently producing unsafe code.
    array_handles  = [(p, ct, iid, ce) for p, ct, iid, ce in out_handles if ce is not None]
    if has_ret and array_handles:
        for ah_p, ah_ct, ah_iid, ah_ce in array_handles:
            # Find the count param and check its properties
            count_name = ah_p.count
            for cp in method.params:
                if cp.name == count_name and cp.indirection >= 1 and cp.output:
                    raise RuntimeError(
                        f'{iface.name}::{method.name}: output COM handle array '
                        f'\'{ah_p.name}\' uses indirect output count '
                        f'\'{count_name}\' on a method that returns {method.return_type}. '
                        f'The generated wrapping loop does not guard against '
                        f'failure — the count may be valid but the array contents '
                        f'are garbage when HRESULT != S_OK.  Either mark this '
                        f'method skip_default in the overlay and write a hand-'
                        f'written override, or add HRESULT-guarded wrapping to '
                        f'the client template.'
                    )
%>\
% if method.skip_default:
/* skip_default: ${iface.name}::${method.name} -- override required.
 * The default body aborts loudly so a missing override is a runtime
 * failure rather than a silent data drop. */
${rt} NPT_STDMETHODCALLTYPE
${tname}(\
void *self\
% if is_agg:
, ${method.return_type} *_ret_out\
% endif
% for p in method.params:
, ${fmt_param_decl(p)}\
% endfor
)
{
    (void)self;
% for p in method.params:
    (void)${p.name};
% endfor
    npt_com_assert_overridden("${iface.name}", "${method.name}");
% if is_agg:
    if (_ret_out) memset(_ret_out, 0, sizeof(*_ret_out));
    return _ret_out;
% elif has_ret:
    return ${fallback_ret(method)};
% endif
}

% else:
${rt} NPT_STDMETHODCALLTYPE
${tname}(\
void *self\
% if is_agg:
, ${method.return_type} *_ret_out\
% endif
% for p in method.params:
, ${fmt_param_decl(p)}\
% endfor
)
{
<%
    # Partition output COM handles into single-value vs array.
    #
    # The encoder allocates a guest_id for each output COM handle slot
    # and stashes it (cast through uintptr_t) into the caller's pointer.
    # After npt_async_ / npt_call_ returns, the client thunk reads that
    # slot back as a uint64_t id and converts it to a proper wrapper via
    # npt_com_get_or_wrap.  Both the sync and async paths share this
    # post-call "stash -> wrap" conversion.
    single_handles = [(p, ct, iid, ce) for p, ct, iid, ce in out_handles if ce is None]
    array_handles  = [(p, ct, iid, ce) for p, ct, iid, ce in out_handles if ce is not None]
%>\
% if single_handles:
% for p, c_type, iid_expr, _ in single_handles:
    ${c_type} *_raw_${p.name} = NULL;
% endfor
    /* Redirect each single-output pointer to a local _raw_ slot so the
     * encoder's stashed guest_id lands somewhere we can read after the
     * submit returns; the original caller-side pointers are restored
     * with the wrapped result at the end. */
% for p, c_type, iid_expr, _ in single_handles:
    ${c_type} **_orig_${p.name} = ${p.name};
    if (${p.name})
        ${p.name} = (${c_type} **)&_raw_${p.name};
% endfor
% endif
% if always_sync:
% if has_ret:
    ${method.return_type} _ret = npt_call_${fname}(\
% else:
    npt_call_${fname}(\
% endif
% for i, a in enumerate(call_args(method)):
${a}${',' if i < len(call_args(method)) - 1 else ''}\
% endfor
);
% else:
    npt_async_${fname}(\
% for i, a in enumerate(call_args(method)):
${a}${',' if i < len(call_args(method)) - 1 else ''}\
% endfor
);
% endif
% if single_handles:
% for p, c_type, iid_expr, _ in single_handles:
    if (_orig_${p.name}) {
% if needs_sync and has_ret and method.return_type == 'HRESULT':
        /* Sync HRESULT: discard the stashed id on failure -- the host
         * won't have registered it, so any wrapper we build would be
         * bogus.  Under the deferred-fatal model an unregistered id
         * surfaces at first use, but returning the right HRESULT here
         * lets well-behaved callers short-circuit without an allocation. */
        if (NPT_SUCCEEDED((HRESULT)_ret) && _raw_${p.name})
% else:
        if (_raw_${p.name})
% endif
            *_orig_${p.name} = (${c_type} *)npt_com_get_or_wrap(
                npt_com_self_device(self),
                ${iid_expr},
                (uint64_t)(uintptr_t)_raw_${p.name},
                (struct npt_com_base *)self);
        else
            *_orig_${p.name} = NULL;
    }
% endfor
% endif
% if array_handles:
    /* Wrap output COM handle arrays in-place.  The encoder stashed the
     * guest-allocated ids in each slot before the submit; convert them
     * to wrappers now. */
% for p, c_type, iid_expr, count_expr in array_handles:
    if (${p.name}) {
        const UINT _n_${p.name} = (UINT)(${count_expr});
        for (UINT _i = 0; _i < _n_${p.name}; _i++) {
            if (${p.name}[_i])
                ${p.name}[_i] = (${c_type} *)npt_com_get_or_wrap(
                    npt_com_self_device(self),
                    ${iid_expr},
                    (uint64_t)(uintptr_t)${p.name}[_i],
                    (struct npt_com_base *)self);
        }
    }
% endfor
% endif
% if is_agg:
    /* COM x64 aggregate-return ABI: copy into the caller's hidden
     * return slot and hand the pointer back. */
    if (_ret_out) *_ret_out = _ret;
    return _ret_out;
% elif has_ret:
% if needs_sync:
    return _ret;
% else:
    /* Async under the deferred-fatal model: assume success.  Host-side
     * failures (OOM, bad arg) leave the guest_id unregistered, so the
     * first method call against the wrapper trips decoder_fatal and
     * unwinds the context cleanly. */
    return (${method.return_type})0 /* S_OK */;
% endif
% endif
}

% endif
% endfor

void
npt_${iface_lower}_fill_default_vtbl(struct npt_${iface_lower}_client_vtbl *dst)
{
    dst->QueryInterface = npt_${iface_lower}_default_QueryInterface;
    dst->AddRef         = npt_${iface_lower}_default_AddRef;
    dst->Release        = npt_${iface_lower}_default_Release;
% for owner, method in chain_methods:
    dst->${method.name} = ${thunk_name(owner.name, method.name)};
% endfor
}

/*
 * Per-interface default vtbl storage.  Populated by
 * npt_${iface_lower}_install_default_vtbl(), which is called once at
 * runtime init time from the global client_table init function.
 */
struct npt_${iface_lower}_client_vtbl npt_${iface_lower}_default_vtbl_storage;

void
npt_${iface_lower}_install_default_vtbl(void)
{
    npt_${iface_lower}_fill_default_vtbl(&npt_${iface_lower}_default_vtbl_storage);
}

void *
npt_${iface_lower}_client_create(struct npt_device *dev, uint64_t host_id)
{
    struct npt_com_base *p = (struct npt_com_base *)npt_alloc(sizeof(*p));
    if (!p)
        return NULL;
    npt_com_base_init(p,
        (const void **)&npt_${iface_lower}_default_vtbl_storage,
        dev, host_id);
    return p;
}

% endfor

#pragma GCC diagnostic pop
