/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Command structs and encode/decode for ${GROUP_NAME}.
 */

#ifndef NPT_PROTOCOL_${SIDE.upper()}_${GUARD}_H
#define NPT_PROTOCOL_${SIDE.upper()}_${GUARD}_H

#include "npt_protocol_${SIDE}_structs.h"
% if IS_HOST:
#include "npt_protocol_host_dispatch_types.h"
% endif
% if IS_GUEST:
/* For npt_com_allocate_next_id -- called inline from every output
 * COM handle's encode path. */
#include "npt_protocol_guest_cs.h"
% endif

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"

<%
def method_full_name(iface_name, method_name):
    return GEN.method_full_name(iface_name, method_name)
%>\
\
## ========== Family-specific structs (if any) ==========
% for ty in FAMILY_STRUCTS:
<% GEN.set_context(ty.name) %>\
<%
    processed = GEN.preprocess_struct_fields(ty.fields)
%>\
/* ${ty.name} (${'union' if ty.category.name == 'UNION' else 'struct'}) */

static inline size_t
npt_sizeof_${ty.name}(const ${ty.name} *val, int max_mode)
{
    size_t size = 0;
${GEN.sizeof_struct_body(ty, processed, 'val->', 'size')}\
    return size;
}

static inline void
npt_encode_${ty.name}(struct npt_cs_encoder *enc, const ${ty.name} *val)
{
% for item in processed:
% if isinstance(item, tuple):
${GEN.encode_bitfield(item[1], 'val->')}
% else:
${GEN.encode_field(item, 'val->')}
% endif
% endfor
}

static inline void
npt_decode_${ty.name}(struct npt_cs_decoder *dec, ${ty.name} *val)
{
% for item in processed:
% if isinstance(item, tuple):
${GEN.decode_bitfield(item[1], 'val->')}
% else:
${GEN.decode_field(item, 'val->', alloc_temp=True)}
% endif
% endfor
}

% if IS_HOST and GEN.type_needs_replace_handle(ty):
static inline void
npt_replace_${ty.name}_handle(struct npt_dispatch_context *ctx, ${ty.name} *val)
{
% for field in ty.fields:
<% code = GEN.replace_handle_field(field, 'val->') %>\
% if code.strip():
${code}
% endif
% endfor
}

% endif
% endfor
\
## ========== Interface methods ==========
% for iface in INTERFACES:
% for method in iface.methods:
<%
    fname = method_full_name(iface.name, method.name)
    GEN.set_context(f'{iface.name}::{method.name}')
    input_params = [p for p in method.params if p.input]
    output_params = [p for p in method.params if p.output]
    _has_ret = GEN.has_return(method.return_type)
    _is_scalar = GEN.is_scalar_return(method.return_type)
    # True when the reply contains a type whose wire size is runtime-
    # unbounded (DRED chain pointers, root-signature parameter arrays,
    # ...).  Such methods cannot use a pre-reserved fixed-size reply
    # slot, so the host encode_reply sets the encoder fatal flag and
    # the guest decode path takes the reply-mismatch branch and
    # returns the documented default for the call's return type.
    _reply_unsupported = GEN.method_reply_is_unsupported(method)
%>\
/*
 * ${iface.name}::${method.name}
 */

struct npt_command_${fname} {
    void *_self;
% for p in method.params:
    ${GEN.c_type(p)} ${p.name};
% endfor
% for p in method.params:
% if GEN.is_output_com_handle_single(p):
    /* Shadow: the guest-allocated id for ${p.name} arrives in the command
     * body (no reply round-trip).  The post-dispatch register pass reads
     * this field and inserts {_guest_id_${p.name} -> *${p.name}} in the
     * context object table. */
    uint64_t _guest_id_${p.name};
% elif GEN.is_output_com_handle_array(p):
    /* Shadow: per-element guest-allocated ids for ${p.name}.  Array and
     * count are temp-allocated from the decoder pool in the same pass
     * that decodes the wire ids. */
    uint64_t *_guest_ids_${p.name};
    uint32_t _guest_id_count_${p.name};
% endif
% endfor
% if _has_ret:
    ${method.return_type} ret;
% endif
};

% if IS_GUEST:
<%
    # All params (input + output) are passed to size/encode functions on the
    # guest side, even though only inputs are used for the command size and
    # only outputs are used for the reply size.
    all_params = method.params
%>\
static inline size_t
npt_sizeof_${fname}(\
% for i, p in enumerate(all_params):
${GEN.c_type(p, force_const=True)} ${p.name}${',' if i < len(all_params) - 1 else ''}\
% endfor
% if not all_params:
void\
% endif
)
{
    /* Command sizing walks caller-supplied input data, so the active
     * discriminator picks the union arm -- max_mode=0. */
    const int max_mode = 0;
    (void)max_mode;  /* unused when the command has no struct/union inputs */
    size_t cmd_size = sizeof(struct npt_command_header);
% for p in all_params:
${GEN.sizeof_input_param(p, '', 'cmd_size')}
% endfor
    return cmd_size;
}

static inline void
npt_encode_${fname}(struct npt_cs_encoder *enc,
${' ' * (len('npt_encode_') + len(fname) + 1)}uint32_t cmd_flags,
${' ' * (len('npt_encode_') + len(fname) + 1)}npt_object_id object_id\
% for p in all_params:
,
${' ' * (len('npt_encode_') + len(fname) + 1)}${GEN.c_type(p)} ${p.name}\
% endfor
)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_${fname}(\
% for i, p in enumerate(all_params):
${p.name}${',' if i < len(all_params) - 1 else ''}\
% endfor
);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_${iface.name},
                                 NPT_METHOD_${fname}),
        .cmd_flags = cmd_flags,
        .object_id = object_id,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
% for p in all_params:
${GEN.encode_input_param(p, '')}
% endfor
}

static inline size_t
npt_sizeof_${fname}_reply(\
% for i, p in enumerate(all_params):
${GEN.c_type(p, force_const=True)} ${p.name}${',' if i < len(all_params) - 1 else ''}\
% endfor
% if not all_params:
void\
% endif
)
{
    /* Reply sizing reserves an upper bound before the host has filled
     * the data, so union arms size as max-of-arms regardless of the
     * caller's discriminator -- max_mode=1. */
    const int max_mode = 1;
    (void)max_mode;  /* unused when the reply has no struct/union outputs */
    size_t cmd_size = sizeof(struct npt_reply_header);
% if _reply_unsupported:
    /* Reply has runtime-unbounded wire size; reserve only the header.
     * Host encode_reply sets the encoder fatal flag and the guest
     * decode path returns the documented default. */
% else:
% if _has_ret and not _is_scalar:
    cmd_size += ${GEN.reply_payload_size_expr(method.return_type)};
% endif
% for p in all_params:
${GEN.sizeof_output_param(p, '', 'cmd_size')}
% endfor
% endif
    return cmd_size;
}

% endif
% if IS_HOST:
static inline void
npt_decode_${fname}_args_temp(struct npt_cs_decoder *dec,
${' ' * (len('npt_decode_') + len(fname) + len('_args_temp') + 1)}struct npt_command_${fname} *args)
{
    /* Decode input parameters from the wire */
% for p in method.params:
${GEN.decode_input_param(p, 'args->')}
% endfor
    /* Allocate temp storage for output-only parameters */
% for p in method.params:
${GEN.alloc_output_param(p, 'args->')}
% endfor
}

static inline void
npt_replace_${fname}_args_handle(struct npt_dispatch_context *ctx, struct npt_command_${fname} *args)
{
% for p in method.params:
<% code = GEN.replace_handle_field(p, 'args->') %>\
% if code.strip():
${code}
% endif
% endfor
}

static inline void
npt_encode_${fname}_reply(struct npt_cs_encoder *enc,
${' ' * (len('npt_encode_') + len(fname) + len('_reply') + 1)}const struct npt_command_${fname} *args)
{
% if _reply_unsupported:
    /* ${iface.name}::${method.name}: reply contains a type with
     * runtime-unbounded wire size (e.g. DRED chain pointers, root-
     * signature parameter arrays).  A pre-reserved fixed-size reply
     * slot cannot represent this without truncating the host data, so
     * the guest gets a clean reply-mismatch via the encoder fatal
     * flag rather than a corrupted stream. */
    npt_cs_encoder_set_fatal(enc);
    return;
% else:
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_${iface.name},
                                 NPT_METHOD_${fname}),
% if _is_scalar:
        .cmd_return = (uint32_t)args->ret,
% else:
        .cmd_return = 0,
% endif
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
% if _has_ret and not _is_scalar:
    npt_encode_${method.return_type}(enc, &args->ret);
% endif
% for p in output_params:
% if p.count_output and method.return_type == 'HRESULT':
    /* ${p.name}: array sized by output count '${p.count_output}'.  On
     * failure the host may have written the required count but left the
     * array contents unpopulated, so only encode elements on success. */
    if ((HRESULT)args->ret >= 0) {
    ${GEN.encode_output_param(p, 'args->')}
    } else {
        npt_encode_array_count(enc, 0);
    }
% else:
${GEN.encode_output_param(p, 'args->')}
% endif
% endfor
% endif
}

<%
    _d_ret = GEN.ret_type_str(method.return_type)
    _d_has_return = GEN.has_return(method.return_type)
    _d_overrides = f'ctx->{iface.name.lower()}_dispatch_overrides'
    _d_pfn_name, _d_typedef_str, _d_call_args, _d_vtable_idx = GEN.vtable_call_args(method, iface.name)
%>\
static inline void
npt_dispatch_${fname}(struct npt_dispatch_context *ctx,
${' ' * (len('npt_dispatch_') + len(fname) + 1)}uint32_t cmd_flags,
${' ' * (len('npt_dispatch_') + len(fname) + 1)}uint64_t object_id)
{
    struct npt_command_${fname} args;
    memset(&args, 0, sizeof(args));

    npt_decode_${fname}_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_${iface.name.upper()});
    if (!args._self) {
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_${fname}_args_handle(ctx, &args);

    ${_d_pfn_name} _original = NPT_COM_VTBL_FUNC(
        ${_d_pfn_name}, npt_com_vtable(args._self),
        NPT_VTBL_${iface.name}_${method.name});

    if (${_d_overrides} && ${_d_overrides}->${method.name}) {
% if _d_has_return:
        args.ret = ${_d_overrides}->${method.name}(ctx, &args, _original);
% else:
        ${_d_overrides}->${method.name}(ctx, &args, _original);
% endif
    } else {
% if _d_has_return:
        args.ret = _original(${_d_call_args});
% else:
        _original(${_d_call_args});
% endif
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */
<% _riid = GEN._riid_expr_for(method.params, 'args.') %>\
% for p in method.params:
<% _reg = GEN.register_output_handle_field(p, 'args.', riid_expr=_riid) %>\
% if _reg.strip():
${_reg}
% endif
% endfor

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_${fname}_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

% endif
## Guest-side reply decode
% if IS_GUEST and (output_params or _has_ret):
static inline void
npt_decode_${fname}_reply(struct npt_cs_decoder *dec\
% for p in output_params:
,
${' ' * (len('npt_decode_') + len(fname) + len('_reply') + 1)}${GEN.c_type(p)} ${p.name}\
% endfor
% if _has_ret:
,
${' ' * (len('npt_decode_') + len(fname) + len('_reply') + 1)}${method.return_type} *ret\
% endif
)
{
    struct npt_reply_header _reply;
    npt_cs_decoder_read(dec, sizeof(_reply), &_reply, sizeof(_reply));
    if (unlikely(_reply.cmd_type != NPT_CMD_TYPE(255, NPT_IFACE_ID_${iface.name},
                                                  NPT_METHOD_${fname}))) {
        /* Host didn't write a reply (decoder fatal, encoder acquire
         * failed, or the reply shmem wasn't populated before the ring
         * head advanced past this command).  Zero reply_type means the
         * reply slot is still at its init value; any other mismatch
         * means reply-stream crossover.  Surface the error to the
         * caller rather than asserting -- the D3D runtime can cope
         * with a failed call, it can't cope with abort(). */
        npt_log("${fname} reply mismatch: got 0x%08x expected 0x%08x",
                (unsigned)_reply.cmd_type,
                (unsigned)NPT_CMD_TYPE(255, NPT_IFACE_ID_${iface.name},
                                       NPT_METHOD_${fname}));
% if _is_scalar and method.return_type == 'HRESULT':
        if (ret) *ret = (HRESULT)0x887A0005 /* DXGI_ERROR_DEVICE_REMOVED */;
% elif _is_scalar:
        if (ret) *ret = (${method.return_type})0;
% elif _has_ret:
        if (ret) memset(ret, 0, sizeof(*ret));
% endif
        return;
    }
% if _is_scalar:
    if (ret) *ret = (${method.return_type})_reply.cmd_return;
% elif _has_ret:
    if (ret) npt_decode_${method.return_type}(dec, ret);
% endif
% for p in output_params:
${GEN.decode_output_param(p, '')}
% endfor
}

% endif
## Guest-side submit/async/call wrappers
% if IS_GUEST:
<%
    call_ret = GEN.ret_type_str(method.return_type)
    fallback_ret = ''
    if _has_ret:
        if method.return_type == 'HRESULT':
            fallback_ret = '(HRESULT)0x8007000E /* E_OUTOFMEMORY */'
        elif _is_scalar:
            fallback_ret = f'({method.return_type})0'
        else:
            fallback_ret = f'({method.return_type}){{0}}'
%>\
static inline void
npt_submit_${fname}(struct npt_ring *ring,
${' ' * (len('npt_submit_') + len(fname) + 1)}uint32_t cmd_flags,
${' ' * (len('npt_submit_') + len(fname) + 1)}npt_object_id object_id\
% for p in all_params:
,
${' ' * (len('npt_submit_') + len(fname) + 1)}${GEN.c_type(p)} ${p.name}\
% endfor
,
${' ' * (len('npt_submit_') + len(fname) + 1)}struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_${fname}(\
% for i, p in enumerate(all_params):
${p.name}${',' if i < len(all_params) - 1 else ''}\
% endfor
);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_${fname}_reply(\
% for i, p in enumerate(all_params):
${p.name}${',' if i < len(all_params) - 1 else ''}\
% endfor
)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_${fname}(enc, cmd_flags, object_id\
% for p in all_params:
, ${p.name}\
% endfor
);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_${fname}(struct npt_ring *ring,
${' ' * (len('npt_async_') + len(fname) + 1)}npt_object_id object_id\
% for p in all_params:
,
${' ' * (len('npt_async_') + len(fname) + 1)}${GEN.c_type(p)} ${p.name}\
% endfor
)
{
    struct npt_ring_submit_command submit;
    npt_submit_${fname}(ring, 0, object_id\
% for p in all_params:
, ${p.name}\
% endfor
, &submit);
}

static inline ${call_ret}
npt_call_${fname}(struct npt_ring *ring,
${' ' * (len('npt_call_') + len(fname) + 1)}npt_object_id object_id\
% for p in all_params:
,
${' ' * (len('npt_call_') + len(fname) + 1)}${GEN.c_type(p)} ${p.name}\
% endfor
)
{
    struct npt_ring_submit_command submit;
    npt_submit_${fname}(ring, NPT_CMD_FLAG_REPLY, object_id\
% for p in all_params:
, ${p.name}\
% endfor
, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
% if _has_ret:
    if (dec) {
<%
    reply_args = [p.name for p in output_params]
    reply_args.append('&_ret')
%>\
        ${method.return_type} _ret;
        npt_decode_${fname}_reply(dec, ${', '.join(reply_args)});
        npt_ring_free_command_reply(ring, &submit);
        return _ret;
    } else {
        return ${fallback_ret};
    }
% else:
    if (dec) {
% if output_params:
        npt_decode_${fname}_reply(dec, ${', '.join(p.name for p in output_params)});
% endif
        npt_ring_free_command_reply(ring, &submit);
    }
% endif
}

% endif
% endfor
% endfor
\
## ========== Top-level functions ==========
% for func in FUNCTIONS:
<%
    fname = func.name
    GEN.set_context(func.name)
    input_params = [p for p in func.params if p.input]
    output_params = [p for p in func.params if p.output]
    _has_ret = GEN.has_return(func.return_type)
    _is_scalar = GEN.is_scalar_return(func.return_type)
    # See the corresponding comment in the method block above.
    _reply_unsupported = GEN.method_reply_is_unsupported(func)
%>\
/*
 * ${func.name} (group ${func.group}, id ${func.id})
 */

struct npt_command_${fname} {
% for p in func.params:
    ${GEN.c_type(p)} ${p.name};
% endfor
% for p in func.params:
% if GEN.is_output_com_handle_single(p):
    /* Shadow: guest-allocated id for ${p.name}. */
    uint64_t _guest_id_${p.name};
% elif GEN.is_output_com_handle_array(p):
    /* Shadow: per-element guest-allocated ids for ${p.name}. */
    uint64_t *_guest_ids_${p.name};
    uint32_t _guest_id_count_${p.name};
% endif
% endfor
% if _has_ret:
    ${func.return_type} ret;
% endif
};

% if IS_GUEST:
<%
    all_params = func.params
%>\
static inline size_t
npt_sizeof_${fname}(\
% for i, p in enumerate(all_params):
${GEN.c_type(p, force_const=True)} ${p.name}${',' if i < len(all_params) - 1 else ''}\
% endfor
% if not all_params:
void\
% endif
)
{
    const int max_mode = 0;
    (void)max_mode;
    size_t cmd_size = sizeof(struct npt_command_header); /* header only, no UUID */
% for p in all_params:
${GEN.sizeof_input_param(p, '', 'cmd_size')}
% endfor
    return cmd_size;
}

static inline void
npt_encode_${fname}(struct npt_cs_encoder *enc,
${' ' * (len('npt_encode_') + len(fname) + 1)}uint32_t cmd_flags\
% for p in all_params:
,
${' ' * (len('npt_encode_') + len(fname) + 1)}${GEN.c_type(p)} ${p.name}\
% endfor
)
{
    const uint32_t _cmd_size = (uint32_t)npt_sizeof_${fname}(\
% for i, p in enumerate(all_params):
${p.name}${',' if i < len(all_params) - 1 else ''}\
% endfor
);
    struct npt_command_header _hdr = {
        .cmd_type = NPT_CMD_TYPE_TOPLEVEL(${func.group}, ${func.id}),
        .cmd_flags = cmd_flags,
        .object_id = 0,
        .cmd_size = _cmd_size,
    };
    npt_cs_encoder_write(enc, sizeof(_hdr), &_hdr, sizeof(_hdr));
% for p in all_params:
${GEN.encode_input_param(p, '')}
% endfor
}

static inline size_t
npt_sizeof_${fname}_reply(\
% for i, p in enumerate(all_params):
${GEN.c_type(p, force_const=True)} ${p.name}${',' if i < len(all_params) - 1 else ''}\
% endfor
% if not all_params:
void\
% endif
)
{
    const int max_mode = 1;
    (void)max_mode;
    size_t cmd_size = sizeof(struct npt_reply_header);
% if _reply_unsupported:
    /* Reply has runtime-unbounded wire size; reserve only the header. */
% else:
% if _has_ret and not _is_scalar:
    cmd_size += ${GEN.reply_payload_size_expr(func.return_type)};
% endif
% for p in all_params:
${GEN.sizeof_output_param(p, '', 'cmd_size')}
% endfor
% endif
    return cmd_size;
}

% endif
% if IS_HOST:
static inline void
npt_decode_${fname}_args_temp(struct npt_cs_decoder *dec,
${' ' * (len('npt_decode_') + len(fname) + len('_args_temp') + 1)}struct npt_command_${fname} *args)
{
    /* Decode input parameters from the wire */
% for p in func.params:
${GEN.decode_input_param(p, 'args->')}
% endfor
    /* Allocate temp storage for output-only parameters */
% for p in func.params:
${GEN.alloc_output_param(p, 'args->')}
% endfor
}

static inline void
npt_replace_${fname}_args_handle(struct npt_dispatch_context *ctx, struct npt_command_${fname} *args)
{
% for p in func.params:
<% code = GEN.replace_handle_field(p, 'args->') %>\
% if code.strip():
${code}
% endif
% endfor
}

static inline void
npt_encode_${fname}_reply(struct npt_cs_encoder *enc,
${' ' * (len('npt_encode_') + len(fname) + len('_reply') + 1)}const struct npt_command_${fname} *args)
{
% if _reply_unsupported:
    /* ${func.name}: reply has runtime-unbounded wire size; cannot use
     * a fixed-size reply slot.  Set the encoder fatal flag so the
     * guest's reply decoder takes the mismatch branch and returns the
     * documented default. */
    npt_cs_encoder_set_fatal(enc);
    return;
% else:
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE_TOPLEVEL(${func.group}, ${func.id}),
% if _is_scalar:
        .cmd_return = (uint32_t)args->ret,
% else:
        .cmd_return = 0,
% endif
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
% if _has_ret and not _is_scalar:
    npt_encode_${func.return_type}(enc, &args->ret);
% endif
% for p in output_params:
% if p.count_output and func.return_type == 'HRESULT':
    /* ${p.name}: array sized by output count '${p.count_output}'.  On
     * failure the host may have written the required count but left the
     * array contents unpopulated, so only encode elements on success. */
    if ((HRESULT)args->ret >= 0) {
    ${GEN.encode_output_param(p, 'args->')}
    } else {
        npt_encode_array_count(enc, 0);
    }
% else:
${GEN.encode_output_param(p, 'args->')}
% endif
% endfor
% endif
}

static inline void
npt_dispatch_${fname}(struct npt_dispatch_context *ctx,
${' ' * (len('npt_dispatch_') + len(fname) + 1)}uint32_t cmd_flags)
{
    struct npt_command_${fname} args;
    memset(&args, 0, sizeof(args));

    npt_decode_${fname}_args_temp(ctx->decoder, &args);
    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    npt_replace_${fname}_args_handle(ctx, &args);

    if (ctx->toplevel_dispatch_overrides &&
        ctx->toplevel_dispatch_overrides->${func.name}) {
% if _has_ret:
        args.ret = ctx->toplevel_dispatch_overrides->${func.name}(ctx, &args);
% else:
        ctx->toplevel_dispatch_overrides->${func.name}(ctx, &args);
% endif
    } else {
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    /* Register any output COM handles.  Top-level functions with a
     * riid + void** pair (CreateDXGIFactory1, D3D12CreateDevice, ...)
     * get runtime type resolution via npt_object_type_from_iid. */
<% _riid = GEN._riid_expr_for(func.params, 'args.') %>\
% for p in func.params:
<% _reg = GEN.register_output_handle_field(p, 'args.', riid_expr=_riid) %>\
% if _reg.strip():
${_reg}
% endif
% endfor

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_${fname}_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

% endif
## Guest-side reply decode for top-level functions
% if IS_GUEST and (output_params or _has_ret):
static inline void
npt_decode_${fname}_reply(struct npt_cs_decoder *dec\
% for p in output_params:
,
${' ' * (len('npt_decode_') + len(fname) + len('_reply') + 1)}${GEN.c_type(p)} ${p.name}\
% endfor
% if _has_ret:
,
${' ' * (len('npt_decode_') + len(fname) + len('_reply') + 1)}${func.return_type} *ret\
% endif
)
{
    struct npt_reply_header _reply;
    npt_cs_decoder_read(dec, sizeof(_reply), &_reply, sizeof(_reply));
    if (unlikely(_reply.cmd_type != NPT_CMD_TYPE_TOPLEVEL(${func.group}, ${func.id}))) {
        /* Host didn't write a reply.  See per-interface equivalent
         * handler above for the reasoning. */
        npt_log("${fname} reply mismatch: got 0x%08x expected 0x%08x",
                (unsigned)_reply.cmd_type,
                (unsigned)NPT_CMD_TYPE_TOPLEVEL(${func.group}, ${func.id}));
% if _is_scalar and func.return_type == 'HRESULT':
        if (ret) *ret = (HRESULT)0x887A0005 /* DXGI_ERROR_DEVICE_REMOVED */;
% elif _is_scalar:
        if (ret) *ret = (${func.return_type})0;
% elif _has_ret:
        if (ret) memset(ret, 0, sizeof(*ret));
% endif
        return;
    }
% if _is_scalar:
    if (ret) *ret = (${func.return_type})_reply.cmd_return;
% elif _has_ret:
    if (ret) npt_decode_${func.return_type}(dec, ret);
% endif
% for p in output_params:
${GEN.decode_output_param(p, '')}
% endfor
}

% endif
## Guest-side submit/async/call wrappers for top-level functions
% if IS_GUEST:
<%
    call_ret = GEN.ret_type_str(func.return_type)
    fallback_ret = ''
    if _has_ret:
        if func.return_type == 'HRESULT':
            fallback_ret = '(HRESULT)0x8007000E /* E_OUTOFMEMORY */'
        elif _is_scalar:
            fallback_ret = f'({func.return_type})0'
        else:
            fallback_ret = f'({func.return_type}){{0}}'
%>\
static inline void
npt_submit_${fname}(struct npt_ring *ring,
${' ' * (len('npt_submit_') + len(fname) + 1)}uint32_t cmd_flags\
% for p in all_params:
,
${' ' * (len('npt_submit_') + len(fname) + 1)}${GEN.c_type(p)} ${p.name}\
% endfor
,
${' ' * (len('npt_submit_') + len(fname) + 1)}struct npt_ring_submit_command *submit)
{
    uint8_t local_cmd_data[NPT_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = npt_sizeof_${fname}(\
% for i, p in enumerate(all_params):
${p.name}${',' if i < len(all_params) - 1 else ''}\
% endfor
);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = (cmd_flags & NPT_CMD_FLAG_REPLY)
        ? npt_sizeof_${fname}_reply(\
% for i, p in enumerate(all_params):
${p.name}${',' if i < len(all_params) - 1 else ''}\
% endfor
)
        : 0;

    struct npt_cs_encoder *enc = npt_ring_submit_command_init(ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        npt_encode_${fname}(enc, cmd_flags\
% for p in all_params:
, ${p.name}\
% endfor
);
        npt_ring_submit_command(ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void
npt_async_${fname}(struct npt_ring *ring\
% for p in all_params:
,
${' ' * (len('npt_async_') + len(fname) + 1)}${GEN.c_type(p)} ${p.name}\
% endfor
)
{
    struct npt_ring_submit_command submit;
    npt_submit_${fname}(ring, 0\
% for p in all_params:
, ${p.name}\
% endfor
, &submit);
}

static inline ${call_ret}
npt_call_${fname}(struct npt_ring *ring\
% for p in all_params:
,
${' ' * (len('npt_call_') + len(fname) + 1)}${GEN.c_type(p)} ${p.name}\
% endfor
)
{
    struct npt_ring_submit_command submit;
    npt_submit_${fname}(ring, NPT_CMD_FLAG_REPLY\
% for p in all_params:
, ${p.name}\
% endfor
, &submit);
    struct npt_cs_decoder *dec = npt_ring_get_command_reply(ring, &submit);
% if _has_ret:
    if (dec) {
<%
    reply_args = [p.name for p in output_params]
    reply_args.append('&_ret')
%>\
        ${func.return_type} _ret;
        npt_decode_${fname}_reply(dec, ${', '.join(reply_args)});
        npt_ring_free_command_reply(ring, &submit);
        return _ret;
    } else {
        return ${fallback_ret};
    }
% else:
    if (dec) {
% if output_params:
        npt_decode_${fname}_reply(dec, ${', '.join(p.name for p in output_params)});
% endif
        npt_ring_free_command_reply(ring, &submit);
    }
% endif
}

% endif
% endfor

#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_${SIDE.upper()}_${GUARD}_H */
