/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Shared protocol definitions: command header, flags, IIDs,
 * interface ids (pinned by npt_interface_ids.json), method indices,
 * and object type enum.
 */

#ifndef NPT_PROTOCOL_DEFS_H
#define NPT_PROTOCOL_DEFS_H

/*
 * The consuming project must provide "npt_cs.h" on the include path.
 * It defines: GUID, npt_object_id, npt_object_type, and related types.
 */
#include "npt_cs.h"

/* ================================================================== */
/* Command/reply headers                                               */
/* ================================================================== */

struct npt_command_header {
    uint32_t cmd_type;
    uint32_t cmd_flags;
    uint64_t object_id;
    uint32_t cmd_size;
    uint32_t reserved;
};

struct npt_reply_header {
    uint32_t cmd_type;
    uint32_t cmd_return;
};

#define NPT_CMD_FLAG_REPLY  0x1u

/*
 * cmd_type bit layout for COM calls:
 *   bits 31:24  group (255 = COM)
 *   bits 23:8   interface_id (pinned from npt_interface_ids.json; 65535 max)
 *   bits  7:0   method wire index within the interface (255 max)
 *
 * Method indices max out around 108 today (ID3D11DeviceContext); the
 * 8-bit field leaves room for ~2.4x growth before we'd have to widen.
 * If an interface ever exceeds 255 methods we bump the wire version
 * and reshape the layout.
 *
 * For toplevel commands (group 1-3), the interface_id/method fields
 * are reused as a flat 24-bit function id via NPT_CMD_TYPE_TOPLEVEL.
 */
#define NPT_CMD_TYPE(group, iface_id, method) \
    (((uint32_t)(group) << 24) | \
     (((uint32_t)(iface_id) & 0xFFFFu) << 8) | \
     ((uint32_t)(method) & 0xFFu))

#define NPT_CMD_TYPE_TOPLEVEL(group, id) \
    (((uint32_t)(group) << 24) | (uint32_t)(id))

/* Stack-allocated buffer size for small commands on the guest side. */
#define NPT_SUBMIT_LOCAL_CMD_SIZE 256

/* Wire-format version, sourced from npt_registry.json's "version"
 * field.  The host advertises this value via
 * virgl_renderer_capset_neptune.wire_format_version; the guest compares
 * against its own copy and refuses to attach on mismatch.  Bump the
 * JSON's version when an incompatible wire change lands. */
#define NPT_PROTOCOL_WIRE_VERSION ${WIRE_VERSION}u

/* ================================================================== */
/* Interface IIDs                                                      */
/* ================================================================== */

% for iface in INTERFACES:
% if iface.uuid:
<%
    d1, d2, d3, d4 = uuid_to_guid_init(iface.uuid)
    d4_str = ', '.join(f'0x{b:02x}' for b in d4)
%>\
static const GUID NPT_IID_${iface.name} = {
    0x${f'{d1:08x}'}, 0x${f'{d2:04x}'}, 0x${f'{d3:04x}'},
    {${d4_str}}
};
% endif
% endfor

/* ================================================================== */
/* Interface ids (pinned by npt_interface_ids.json)                    */
/* ================================================================== */
/*
 * Each interface carries a stable 16-bit id used:
 *   - as the routing key in the cmd_type middle bits (see
 *     NPT_CMD_TYPE above);
 *   - as the object-type tag passed to npt_cs_handle_lookup and
 *     stored in the host's object_table.
 *
 * The id space is managed by neptune-protocol/npt_interface_ids.json.
 * See that file for the retirement policy (retired ids stay present so
 * their values are never reused -- same convention as protobuf
 * field numbers).
 */

% for iface in INTERFACES:
% if iface.uuid:
#define NPT_IFACE_ID_${iface.name}  ((uint16_t)${iface.interface_id}u)
% endif
% endfor

/* ================================================================== */
/* Method wire indices (per-interface, 0-based)                        */
/* ================================================================== */

% for iface in INTERFACES:
% for method in iface.methods:
#define NPT_METHOD_${iface.name}_${method.name}  ${method.wire_index}
% endfor
% endfor

/* ================================================================== */
/* Method absolute COM vtable slots (including inherited slots)        */
/* ================================================================== */

% for iface in INTERFACES:
% for method in iface.methods:
#define NPT_VTBL_${iface.name}_${method.name}  ${method.vtable_index}
% endfor
% endfor

/* ================================================================== */
/* Object type tags (aliased onto the pinned interface ids)            */
/* ================================================================== */
/*
 * NPT_OBJECT_TYPE_* is the runtime's name for the same value that
 * NPT_IFACE_ID_* uses on the wire.  One pinned id per interface; the
 * two macro families coexist so runtime call sites can keep their
 * descriptive names (npt_cs_handle_lookup(..., NPT_OBJECT_TYPE_FOO))
 * while the wire routing uses NPT_IFACE_ID_Foo.
 *
 * Reserved values:
 *   0  INVALID / uninitialized.  npt_context_register_object refuses
 *      to register a handle whose type is 0, so this doubles as the
 *      "don't know, don't register" signal.
 */
#define NPT_OBJECT_TYPE_INVALID  ((npt_object_type)0)

% for iface in INTERFACES:
% if iface.uuid:
#define NPT_OBJECT_TYPE_${iface.name.upper()}  ((npt_object_type)NPT_IFACE_ID_${iface.name})
% endif
% endfor
<%
    _max_iid = max((iface.interface_id for iface in INTERFACES if iface.uuid), default=0)
%>\
#define NPT_OBJECT_TYPE_COUNT  ((npt_object_type)${_max_iid + 1})

/* ================================================================== */
/* Object type parent table                                            */
/* ================================================================== */
/*
 * Indexed by NPT_OBJECT_TYPE_* (= NPT_IFACE_ID_*).  Entry value is the
 * parent interface's type tag, or 0 for "no parent in the registry"
 * (i.e. the interface inherits from IUnknown as far as we represent
 * it, and the walk terminates cleanly).  Unused id slots (gaps left
 * by retired ids in npt_interface_ids.json) default to 0, which
 * terminates the walk safely.
 *
 * Used by the runtime handle-lookup to accept a derived-type pointer
 * where a base-type pointer is expected (e.g. ID3D11Buffer passed
 * where ID3D11Resource is expected -- a valid COM upcast).
 */
static const npt_object_type npt_object_type_parent[NPT_OBJECT_TYPE_COUNT] = {
% for iface in INTERFACES:
% if iface.uuid:
<%
    parent = GEN.parent_interface_name(iface)
    parent_macro = f'NPT_OBJECT_TYPE_{parent.upper()}' if parent else '0'
%>\
    [NPT_OBJECT_TYPE_${iface.name.upper()}] = ${parent_macro},
% endif
% endfor
};

/* ================================================================== */
/* IID -> object type lookup                                           */
/* ================================================================== */
/*
 * Resolve a caller-supplied REFIID (e.g. the riid argument to
 * CreateDXGIFactory1 or IUnknown::QueryInterface) to the matching
 * NPT_OBJECT_TYPE_* value.  Returns NPT_OBJECT_TYPE_IUNKNOWN (= the
 * "untyped" sentinel) when the IID isn't one of the interfaces in
 * the registry -- the consumer's handle table treats IUNKNOWN as
 * permissive, so unknown IIDs don't cause a legitimate caller to
 * fail.
 *
 * Static table with linear search is fine here: ~200 interfaces,
 * only called on object-creation paths.
 */
static inline npt_object_type
npt_object_type_from_iid(const GUID *iid)
{
    if (!iid)
        return NPT_OBJECT_TYPE_IUNKNOWN;

    static const struct {
        const GUID *iid;
        npt_object_type type;
    } table[] = {
% for iface in INTERFACES:
% if iface.uuid:
        { &NPT_IID_${iface.name}, NPT_OBJECT_TYPE_${iface.name.upper()} },
% endif
% endfor
    };

    for (size_t i = 0; i < sizeof(table) / sizeof(table[0]); i++) {
        const GUID *a = iid;
        const GUID *b = table[i].iid;
        if (a->Data1 == b->Data1 && a->Data2 == b->Data2 &&
            a->Data3 == b->Data3 &&
            a->Data4[0] == b->Data4[0] && a->Data4[1] == b->Data4[1] &&
            a->Data4[2] == b->Data4[2] && a->Data4[3] == b->Data4[3] &&
            a->Data4[4] == b->Data4[4] && a->Data4[5] == b->Data4[5] &&
            a->Data4[6] == b->Data4[6] && a->Data4[7] == b->Data4[7])
            return table[i].type;
    }
    return NPT_OBJECT_TYPE_IUNKNOWN;
}

#endif /* NPT_PROTOCOL_DEFS_H */
