/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Dispatch routing: per-interface method switch, UUID dispatch,
 * top-level function dispatch, and main entry point.
 *
 * Per-method dispatch functions are in the per-family command headers.
 * Type definitions (PFN, overrides, context) are in dispatch_types.h.
 */

#ifndef NPT_PROTOCOL_HOST_DISPATCH_H
#define NPT_PROTOCOL_HOST_DISPATCH_H

% for inc in INCLUDES:
#include "npt_protocol_host_${inc}.h"
% endfor

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"

<%
def method_full_name(iface_name, method_name):
    return GEN.method_full_name(iface_name, method_name)
%>\

/* ================================================================== */
/* Per-interface method switch                                         */
/* ================================================================== */

% for iface in ALL_INTERFACES:
static inline void
npt_dispatch_${iface.name}_method(struct npt_dispatch_context *ctx,
${' ' * (len('npt_dispatch_') + len(iface.name) + len('_method') + 1)}uint8_t method_index,
${' ' * (len('npt_dispatch_') + len(iface.name) + len('_method') + 1)}uint32_t cmd_flags,
${' ' * (len('npt_dispatch_') + len(iface.name) + len('_method') + 1)}uint64_t object_id)
{
    switch (method_index) {
% for method in iface.methods:
    case ${method.wire_index}:
        npt_dispatch_${method_full_name(iface.name, method.name)}(ctx, cmd_flags, object_id);
        break;
% endfor
    default:
        npt_cs_decoder_set_fatal(ctx->decoder);
        break;
    }
}

% endfor

/* ================================================================== */
/* COM dispatch (direct switch on pinned interface_id)                 */
/* ================================================================== */
/*
 * interface_id is pinned in neptune-protocol/npt_interface_ids.json
 * and extracted from bits 23:8 of cmd_type (see NPT_CMD_TYPE in
 * npt_protocol_defs.h).  The compiler lowers this single large
 * switch into a jump table; no GUID comparison, no hash collision
 * handling, no second-level match.
 */

static inline void
npt_dispatch_com_call(struct npt_dispatch_context *ctx,
                      uint16_t interface_id,
                      uint8_t method_index,
                      uint32_t cmd_flags,
                      uint64_t object_id)
{
    switch (interface_id) {
% for iface in ALL_INTERFACES:
    case NPT_IFACE_ID_${iface.name}:
        npt_dispatch_${iface.name}_method(ctx, method_index, cmd_flags, object_id);
        return;
% endfor
    default:
        break;
    }
    npt_cs_decoder_set_fatal(ctx->decoder);
}

/* ================================================================== */
/* Top-level function dispatch                                        */
/* ================================================================== */

static inline void
npt_dispatch_toplevel(struct npt_dispatch_context *ctx,
                      uint32_t group, uint32_t func_id,
                      uint32_t cmd_flags)
{
<%
    # Group functions by group number
    func_groups = {}
    for func in ALL_FUNCTIONS:
        func_groups.setdefault(func.group, []).append(func)
%>\
    switch (group) {
% for g in sorted(func_groups.keys()):
    case ${g}:
        switch (func_id) {
% for func in func_groups[g]:
        case ${func.id}:
            npt_dispatch_${func.name}(ctx, cmd_flags);
            break;
% endfor
        default:
            npt_cs_decoder_set_fatal(ctx->decoder);
            break;
        }
        break;
% endfor
    default:
        npt_cs_decoder_set_fatal(ctx->decoder);
        break;
    }
}

/* ================================================================== */
/* Main dispatch entry point                                           */
/* ================================================================== */

static inline void
npt_dispatch_command(struct npt_dispatch_context *ctx)
{
    struct npt_command_header _hdr;
    npt_cs_decoder_read(ctx->decoder, sizeof(_hdr), &_hdr, sizeof(_hdr));

    const uint32_t _group = (_hdr.cmd_type >> 24) & 0xFF;

    if (_group == 255) {
        /* COM call: interface_id and method_index come straight from
         * cmd_type (no per-call GUID on the wire; pinned interface IDs
         * live in neptune-protocol/npt_interface_ids.json). */
        const uint16_t _interface_id = (_hdr.cmd_type >> 8) & 0xFFFFu;
        const uint8_t _method_index = _hdr.cmd_type & 0xFFu;
        npt_dispatch_com_call(ctx, _interface_id, _method_index,
                              _hdr.cmd_flags, _hdr.object_id);
<%
    _func_groups = set(f.group for f in ALL_FUNCTIONS)
    _min_group = min(_func_groups) if _func_groups else 0
    _max_group = max(_func_groups) if _func_groups else 0
%>\
    } else if (_group >= ${_min_group} && _group <= ${_max_group}) {
        const uint32_t _func_id = _hdr.cmd_type & 0x00FFFFFF;
        npt_dispatch_toplevel(ctx, _group, _func_id, _hdr.cmd_flags);
    } else {
        npt_cs_decoder_set_fatal(ctx->decoder);
    }

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        npt_log("dispatch error for cmd_type=0x%08x", _hdr.cmd_type);
}

#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_HOST_DISPATCH_H */
