/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Dispatch type definitions: PFN typedefs, override structs, dispatch context.
 * Included before per-family command headers so dispatch functions can
 * reference the context and override types.
 */

#ifndef NPT_PROTOCOL_HOST_DISPATCH_TYPES_H
#define NPT_PROTOCOL_HOST_DISPATCH_TYPES_H

#include "npt_protocol_host_structs.h"

<%
def method_full_name(iface_name, method_name):
    return GEN.method_full_name(iface_name, method_name)

def overrides_name(iface_name):
    return f'npt_dispatch_{iface_name.lower()}_overrides'
%>\

/* ================================================================== */
/* Forward declarations for command structs                            */
/* ================================================================== */

% for iface in ALL_INTERFACES:
% for method in iface.methods:
struct npt_command_${method_full_name(iface.name, method.name)};
% endfor
% endfor
% for func in ALL_FUNCTIONS:
struct npt_command_${func.name};
% endfor

/* ================================================================== */
/* COM vtable function pointer typedefs                                */
/* ================================================================== */

% for iface in ALL_INTERFACES:
% for method in iface.methods:
<%
    pfn_name, typedef_str, call_args, vtable_idx = GEN.vtable_call_args(method, iface.name)
%>\
${typedef_str};
% endfor
% endfor

/* ================================================================== */
/* Top-level function pointer typedefs                                 */
/* ================================================================== */

% for func in ALL_FUNCTIONS:
${GEN.function_pfn_typedef(func)};
% endfor

/* ================================================================== */
/* Per-interface dispatch overrides structs                            */
/* ================================================================== */

% for iface in ALL_INTERFACES:
struct ${overrides_name(iface.name)} {
% for method in iface.methods:
<%
    fname = method_full_name(iface.name, method.name)
    ret = GEN.ret_type_str(method.return_type)
    pfn_name = GEN.pfn_typedef_name(iface.name, method.name)
%>\
    ${ret} (*${method.name})(struct npt_dispatch_context *ctx,
        ${'  ' * len(method.name)}struct npt_command_${fname} *args,
        ${'  ' * len(method.name)}${pfn_name} original);
% endfor
};

% endfor

/* ================================================================== */
/* Top-level function dispatch overrides                               */
/* ================================================================== */

struct npt_dispatch_toplevel_overrides {
% for func in ALL_FUNCTIONS:
<%
    ret = GEN.ret_type_str(func.return_type)
%>\
    ${ret} (*${func.name})(struct npt_dispatch_context *ctx,
        ${'  ' * len(func.name)}struct npt_command_${func.name} *args);
% endfor
};

/* ================================================================== */
/* Dispatch context                                                    */
/* ================================================================== */

struct npt_dispatch_context {
    /*
     * Opaque consumer back-pointer.  The consumer (host renderer) sets
     * this to its per-context state when it initializes the dispatch
     * context, then override functions read it back to recover the
     * outer struct (e.g. `struct npt_context *`).
     */
    void *data;

    struct npt_cs_decoder *decoder;
    struct npt_cs_encoder *encoder;

% for iface in ALL_INTERFACES:
    struct ${overrides_name(iface.name)} *${iface.name.lower()}_dispatch_overrides;
% endfor
    struct npt_dispatch_toplevel_overrides *toplevel_dispatch_overrides;
};

#endif /* NPT_PROTOCOL_HOST_DISPATCH_TYPES_H */
