/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 * Source: ${GIT_COMMIT}
 *
 * Umbrella header for guest-side (encoder).
 */

#ifndef NPT_PROTOCOL_GUEST_H
#define NPT_PROTOCOL_GUEST_H

#include "npt_protocol_directx_types.h"
#include "npt_protocol_defs.h"
#include "npt_protocol_common_types.h"
#include "npt_protocol_guest_structs.h"
% for inc in INCLUDES:
#include "npt_protocol_guest_${inc}.h"
% endfor

#endif /* NPT_PROTOCOL_GUEST_H */
