/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 * Source: ${GIT_COMMIT}
 *
 * Umbrella header for host-side (decoder + dispatch).
 */

#ifndef NPT_PROTOCOL_HOST_H
#define NPT_PROTOCOL_HOST_H

#include "npt_protocol_directx_types.h"
#include "npt_protocol_defs.h"
#include "npt_protocol_common_types.h"
#include "npt_protocol_host_structs.h"
#include "npt_protocol_host_dispatch_types.h"
% for inc in INCLUDES:
#include "npt_protocol_host_${inc}.h"
% endfor
#include "npt_protocol_host_dispatch.h"

#endif /* NPT_PROTOCOL_HOST_H */
