/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Struct/union sizeof/encode/decode functions.
 */

#ifndef NPT_PROTOCOL_${SIDE.upper()}_STRUCTS_H
#define NPT_PROTOCOL_${SIDE.upper()}_STRUCTS_H

#include "npt_protocol_common_types.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"

/* Forward declarations: structs with mutual recursion (e.g.
 * D3D12_STATE_SUBOBJECT ↔ D3D12_SUBOBJECT_TO_EXPORTS_ASSOCIATION via the
 * tagged-union overlay) need every helper visible before any body emits. */
% for ty in STRUCT_TYPES:
static inline size_t npt_sizeof_${ty.name}(const ${ty.name} *val, int max_mode);
static inline void npt_encode_${ty.name}(struct npt_cs_encoder *enc, const ${ty.name} *val);
static inline void npt_decode_${ty.name}(struct npt_cs_decoder *dec, ${ty.name} *val);
% if IS_HOST and GEN.type_needs_replace_handle(ty):
static inline void npt_replace_${ty.name}_handle(struct npt_dispatch_context *ctx, ${ty.name} *val);
% endif
% endfor

% for ty in STRUCT_TYPES:
<% GEN.set_context(ty.name) %>\
<%
    processed = GEN.preprocess_struct_fields(ty.fields)
%>\
/* ${ty.name} (${'union' if ty.category.name == 'UNION' else 'struct'}) */

static inline size_t
npt_sizeof_${ty.name}(const ${ty.name} *val, int max_mode)
{
    size_t size = 0;
${GEN.sizeof_struct_body(ty, processed, 'val->', 'size')}\
    return size;
}

static inline void
npt_encode_${ty.name}(struct npt_cs_encoder *enc, const ${ty.name} *val)
{
% for item in processed:
% if isinstance(item, tuple):
${GEN.encode_bitfield(item[1], 'val->')}
% else:
${GEN.encode_field(item, 'val->')}
% endif
% endfor
}

static inline void
npt_decode_${ty.name}(struct npt_cs_decoder *dec, ${ty.name} *val)
{
% for item in processed:
% if isinstance(item, tuple):
${GEN.decode_bitfield(item[1], 'val->')}
% else:
${GEN.decode_field(item, 'val->', alloc_temp=True)}
% endif
% endfor
}

% if IS_HOST and GEN.type_needs_replace_handle(ty):
static inline void
npt_replace_${ty.name}_handle(struct npt_dispatch_context *ctx, ${ty.name} *val)
{
% for field in ty.fields:
<% code = GEN.replace_handle_field(field, 'val->') %>\
% if code.strip():
${code}
% endif
% endfor
}

% endif
% endfor

#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_${SIDE.upper()}_STRUCTS_H */
