/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Scalar/enum/alias sizeof/encode/decode functions.
 */

#ifndef NPT_PROTOCOL_COMMON_TYPES_H
#define NPT_PROTOCOL_COMMON_TYPES_H

#include "npt_protocol_defs.h"
#include "npt_protocol_common_cs_helpers.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"


% for ty in ENUM_TYPES:
/* ${ty.name} */

static inline size_t
npt_sizeof_${ty.name}(const ${ty.name} *val, int max_mode)
{
    return npt_sizeof_int32_t((const int32_t *)val, max_mode);
}

static inline void
npt_encode_${ty.name}(struct npt_cs_encoder *enc, const ${ty.name} *val)
{
    npt_encode_int32_t(enc, (const int32_t *)val);
}

static inline void
npt_decode_${ty.name}(struct npt_cs_decoder *dec, ${ty.name} *val)
{
    npt_decode_int32_t(dec, (int32_t *)val);
}

static inline size_t
npt_sizeof_${ty.name}_array(const ${ty.name} *val, uint32_t count)
{
    return npt_sizeof_int32_t_array((const int32_t *)val, count);
}

static inline void
npt_encode_${ty.name}_array(struct npt_cs_encoder *enc,
                             const ${ty.name} *val, uint32_t count)
{
    npt_encode_int32_t_array(enc, (const int32_t *)val, count);
}

static inline void
npt_decode_${ty.name}_array(struct npt_cs_decoder *dec,
                             ${ty.name} *val, uint32_t count)
{
    npt_decode_int32_t_array(dec, (int32_t *)val, count);
}

% endfor

/*
 * Forward declarations for struct/union encode/decode functions.
 * These are defined in structs.h (included after this file) but
 * aliases below may delegate to them.
 */
% for ty in STRUCT_TYPES:
static inline size_t npt_sizeof_${ty.name}(const ${ty.name} *val, int max_mode);
static inline void npt_encode_${ty.name}(struct npt_cs_encoder *enc, const ${ty.name} *val);
static inline void npt_decode_${ty.name}(struct npt_cs_decoder *dec, ${ty.name} *val);
% endfor

/*
 * Type aliases -- delegate to the base primitive, enum, or struct.
 */

% for ty in ALIAS_TYPES:
<%
    # Resolve to a target that has encode/decode functions.
    resolved = REG.resolve_alias_chain(ty.alias_target)
    target_type = REG.get_type(ty.alias_target)
    if target_type and (target_type.category.name in ('ALIAS', 'ENUM', 'STRUCT', 'UNION') or ty.alias_target in PRIMITIVE_NAMES):
        delegate = ty.alias_target
    else:
        delegate = resolved
    delegate_type = REG.get_type(delegate)
    delegate_is_struct = delegate_type and delegate_type.category.name in ('STRUCT', 'UNION')
    # Array variants for primitives, enums, and aliases that resolve to primitives
    has_array = (delegate in PRIMITIVE_NAMES or
                 (delegate_type and delegate_type.category.name == 'ENUM') or
                 (delegate_type and delegate_type.category.name == 'ALIAS' and
                  REG.resolve_alias_chain(delegate) in PRIMITIVE_NAMES))
%>\
/* ${ty.name} (alias for ${delegate}) */

static inline size_t
npt_sizeof_${ty.name}(const ${ty.name} *val, int max_mode)
{
    return npt_sizeof_${delegate}((const ${delegate} *)val, max_mode);
}

static inline void
npt_encode_${ty.name}(struct npt_cs_encoder *enc, const ${ty.name} *val)
{
    npt_encode_${delegate}(enc, (const ${delegate} *)val);
}

static inline void
npt_decode_${ty.name}(struct npt_cs_decoder *dec, ${ty.name} *val)
{
    npt_decode_${delegate}(dec, (${delegate} *)val);
}

% if has_array:
static inline size_t
npt_sizeof_${ty.name}_array(const ${ty.name} *val, uint32_t count)
{
    return npt_sizeof_${delegate}_array((const ${delegate} *)val, count);
}

static inline void
npt_encode_${ty.name}_array(struct npt_cs_encoder *enc,
                             const ${ty.name} *val, uint32_t count)
{
    npt_encode_${delegate}_array(enc, (const ${delegate} *)val, count);
}

static inline void
npt_decode_${ty.name}_array(struct npt_cs_decoder *dec,
                             ${ty.name} *val, uint32_t count)
{
    npt_decode_${delegate}_array(dec, (${delegate} *)val, count);
}

% endif
% endfor

#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_COMMON_TYPES_H */
